//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CocoWebApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table_Coco_People
    {
        public long id_member { get; set; }
        public string first_name { get; set; }
        public string middle_name { get; set; }
        public string last_name { get; set; }
        public int code_postal { get; set; }
        public string city { get; set; }
        public long telephone { get; set; }
        public string addresse { get; set; }
    }
}
